import type { QuizQuestion, KnowledgeSubject, Grade } from '../types';

export const KNOWLEDGE_SUBJECTS: { value: KnowledgeSubject; label: string; icon: string; description: string }[] = [
  { value: 'science', label: 'Science', icon: '🔬', description: 'Explore plants, animals, the human body, and the world around us' },
  { value: 'gk', label: 'General Knowledge', icon: '🌍', description: 'Discover facts about India, the world, and everyday life' },
  { value: 'health', label: 'Health Education', icon: '🩺', description: 'Learn healthy habits for a happy, strong body and mind' },
];

const SCIENCE_QUESTIONS: Omit<QuizQuestion, 'id'>[] = [
  // Grade 2
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'Plants need sunlight, water and air to grow.', correctAnswer: 'True', explanation: 'Plants use sunlight, water, and air (carbon dioxide) to make their own food.', category: 'Plants' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'Which part of the plant absorbs water from the soil?', options: ['Leaf', 'Root', 'Flower', 'Stem'], correctAnswer: 'Root', explanation: 'Roots grow underground and soak up water and nutrients for the plant.', category: 'Plants' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'Fish breathe using lungs, just like humans.', correctAnswer: 'False', explanation: 'Fish breathe using gills, which take in oxygen from water.', category: 'Animals' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'How many senses do humans have?', options: ['3', '4', '5', '6'], correctAnswer: '5', explanation: 'The five senses are sight, hearing, smell, taste, and touch.', category: 'Human Body' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'The sun rises in the west.', correctAnswer: 'False', explanation: 'The sun rises in the east and sets in the west.', category: 'Earth & Sky' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'Which of these is a living thing?', options: ['Rock', 'Chair', 'Tree', 'Table'], correctAnswer: 'Tree', explanation: 'Living things grow, breathe, and reproduce — a tree is alive, but rocks, chairs, and tables are not.', category: 'Living Things' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'Baby dogs are called puppies.', correctAnswer: 'True', explanation: 'A baby dog is called a puppy.', category: 'Animals' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'What do we call animals that eat only plants?', options: ['Carnivores', 'Herbivores', 'Omnivores', 'Predators'], correctAnswer: 'Herbivores', explanation: 'Herbivores are animals that eat only plants, like cows and rabbits.', category: 'Animals' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'We should wash our hands before eating food.', correctAnswer: 'True', explanation: 'Washing hands removes germs and keeps us healthy.', category: 'Human Body' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'Which season comes after winter?', options: ['Summer', 'Spring', 'Autumn', 'Monsoon'], correctAnswer: 'Spring', explanation: 'In most places, spring follows winter, bringing warmer weather and blooming flowers.', category: 'Earth & Sky' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'The moon gives out its own light.', correctAnswer: 'False', explanation: 'The moon reflects sunlight; it does not produce its own light.', category: 'Earth & Sky' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'What do bees make?', options: ['Milk', 'Honey', 'Silk', 'Wool'], correctAnswer: 'Honey', explanation: 'Bees collect nectar from flowers and turn it into honey.', category: 'Animals' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'All birds can fly.', correctAnswer: 'False', explanation: 'Some birds, like penguins and ostriches, cannot fly.', category: 'Animals' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'Which organ pumps blood around our body?', options: ['Brain', 'Lungs', 'Heart', 'Stomach'], correctAnswer: 'Heart', explanation: 'The heart pumps blood through our body, carrying oxygen and nutrients.', category: 'Human Body' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'Ice is the solid form of water.', correctAnswer: 'True', explanation: 'When water freezes, it turns into ice, a solid.', category: 'Matter' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'Where do polar bears live?', options: ['Desert', 'Rainforest', 'Cold Arctic regions', 'Ocean floor'], correctAnswer: 'Cold Arctic regions', explanation: 'Polar bears live in cold, icy places near the North Pole.', category: 'Animals' },
  { subject: 'science', grade: 'grade2', type: 'truefalse', question: 'Plants make their own food.', correctAnswer: 'True', explanation: 'Plants make their food through a process called photosynthesis using sunlight.', category: 'Plants' },
  { subject: 'science', grade: 'grade2', type: 'mcq', question: 'What is the color of a healthy plant leaf?', options: ['Brown', 'Yellow', 'Green', 'Red'], correctAnswer: 'Green', explanation: 'Leaves are green because they contain a substance called chlorophyll, which helps them make food.', category: 'Plants' },

  // Grade 3
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'What are the three states of matter?', options: ['Solid, Liquid, Gas', 'Hot, Cold, Warm', 'Big, Small, Medium', 'Fast, Slow, Still'], correctAnswer: 'Solid, Liquid, Gas', explanation: 'Matter exists in three main states: solid, liquid, and gas.', category: 'Matter' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'Water boils and turns into water vapour (gas) when heated.', correctAnswer: 'True', explanation: 'Heating water causes it to change from a liquid into a gas called water vapour.', category: 'Matter' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'Which part of the plant makes food using sunlight?', options: ['Root', 'Stem', 'Leaf', 'Flower'], correctAnswer: 'Leaf', explanation: 'Leaves contain chlorophyll and use sunlight to make food through photosynthesis.', category: 'Plants' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'Animals that eat both plants and meat are called omnivores.', correctAnswer: 'True', explanation: 'Omnivores, like humans and bears, eat both plants and animals.', category: 'Animals' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'Which of these is a mammal?', options: ['Crocodile', 'Dolphin', 'Eagle', 'Frog'], correctAnswer: 'Dolphin', explanation: 'Dolphins are mammals — they breathe air and feed their babies milk, even though they live in water.', category: 'Animals' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'Insects have six legs.', correctAnswer: 'True', explanation: 'All insects have three body parts and six legs.', category: 'Animals' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'What is the hardest natural substance on Earth?', options: ['Iron', 'Gold', 'Diamond', 'Wood'], correctAnswer: 'Diamond', explanation: 'Diamond is the hardest known natural material.', category: 'Materials' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'A push and a pull are both examples of a force.', correctAnswer: 'True', explanation: 'Both pushing and pulling an object are forces that can move or stop it.', category: 'Forces' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'Which organ helps us breathe?', options: ['Heart', 'Lungs', 'Kidney', 'Liver'], correctAnswer: 'Lungs', explanation: 'Lungs take in oxygen from the air and release carbon dioxide.', category: 'Human Body' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'Which simple machine is a see-saw an example of?', options: ['Wheel', 'Lever', 'Pulley', 'Screw'], correctAnswer: 'Lever', explanation: 'A see-saw is a lever — it pivots at a fixed point to help lift weight.', category: 'Forces' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'The Earth is the planet closest to the Sun.', correctAnswer: 'False', explanation: 'Mercury is the closest planet to the Sun, not Earth.', category: 'Space' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'What do we call water falling from clouds?', options: ['Fog', 'Rain', 'Steam', 'Dew'], correctAnswer: 'Rain', explanation: 'When water droplets in clouds become heavy, they fall as rain.', category: 'Earth & Sky' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'Bones and muscles work together to help us move.', correctAnswer: 'True', explanation: 'Muscles pull on bones, letting us walk, run, and move our bodies.', category: 'Human Body' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'Which of these is NOT a source of energy?', options: ['Sun', 'Wind', 'Rock', 'Water'], correctAnswer: 'Rock', explanation: 'Sun, wind, and water can all be used as sources of energy, but ordinary rocks cannot.', category: 'Energy' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'All plants need soil to grow.', correctAnswer: 'False', explanation: 'Some plants can grow in water alone; soil is common but not strictly required for every plant.', category: 'Plants' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'What is the main gas that plants take in from the air to make food?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], correctAnswer: 'Carbon dioxide', explanation: 'Plants absorb carbon dioxide from the air to make food during photosynthesis.', category: 'Plants' },
  { subject: 'science', grade: 'grade3', type: 'truefalse', question: 'Sound cannot travel through water.', correctAnswer: 'False', explanation: 'Sound travels through water — in fact, it travels faster in water than in air.', category: 'Forces' },
  { subject: 'science', grade: 'grade3', type: 'mcq', question: 'Which of these animals is a reptile?', options: ['Frog', 'Snake', 'Fish', 'Butterfly'], correctAnswer: 'Snake', explanation: 'Snakes are reptiles — cold-blooded animals with scaly skin.', category: 'Animals' },
];

const GK_QUESTIONS: Omit<QuizQuestion, 'id'>[] = [
  // Grade 2
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'What is the capital of India?', options: ['Mumbai', 'Delhi', 'Kolkata', 'Chennai'], correctAnswer: 'Delhi', explanation: 'New Delhi is the capital city of India.', category: 'India' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'The Indian flag has three colours.', correctAnswer: 'True', explanation: 'The Indian flag has saffron, white, and green, with a blue wheel (Ashoka Chakra) in the middle.', category: 'India' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: "What is India's national animal?", options: ['Lion', 'Tiger', 'Elephant', 'Peacock'], correctAnswer: 'Tiger', explanation: "The Bengal Tiger is India's national animal.", category: 'India' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: "What is India's national bird?", options: ['Sparrow', 'Peacock', 'Eagle', 'Parrot'], correctAnswer: 'Peacock', explanation: "The peacock is India's national bird, known for its colourful feathers.", category: 'India' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'There are 7 days in a week.', correctAnswer: 'True', explanation: 'A week has seven days: Monday through Sunday.', category: 'General' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'How many colours are there in a rainbow?', options: ['5', '6', '7', '8'], correctAnswer: '7', explanation: 'A rainbow has seven colours: red, orange, yellow, green, blue, indigo, and violet.', category: 'World' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'The Earth has only one moon.', correctAnswer: 'True', explanation: 'Earth has one natural satellite, the Moon.', category: 'World' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'Which is the largest ocean in the world?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], correctAnswer: 'Pacific', explanation: 'The Pacific Ocean is the largest and deepest ocean on Earth.', category: 'World' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'A triangle has four sides.', correctAnswer: 'False', explanation: 'A triangle has three sides, not four.', category: 'General' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'Which animal is known as the "Ship of the Desert"?', options: ['Horse', 'Camel', 'Donkey', 'Elephant'], correctAnswer: 'Camel', explanation: 'Camels can travel long distances in the desert without water, so they are called the "Ship of the Desert."', category: 'World' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'India is a continent.', correctAnswer: 'False', explanation: 'India is a country; it is part of the continent of Asia.', category: 'India' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'What do we call a baby cat?', options: ['Puppy', 'Kitten', 'Cub', 'Calf'], correctAnswer: 'Kitten', explanation: 'A baby cat is called a kitten.', category: 'General' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: "What is India's national flower?", options: ['Rose', 'Sunflower', 'Lotus', 'Marigold'], correctAnswer: 'Lotus', explanation: "The lotus is India's national flower, symbolising purity.", category: 'India' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'There are 12 months in a year.', correctAnswer: 'True', explanation: 'A year has twelve months, from January to December.', category: 'General' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'Which shape has no corners?', options: ['Square', 'Triangle', 'Circle', 'Rectangle'], correctAnswer: 'Circle', explanation: 'A circle is a round shape with no corners or edges.', category: 'General' },
  { subject: 'gk', grade: 'grade2', type: 'truefalse', question: 'Ice cream is a fruit.', correctAnswer: 'False', explanation: 'Ice cream is a dessert made from milk and sugar, not a fruit.', category: 'General' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'What is the tallest animal in the world?', options: ['Elephant', 'Giraffe', 'Horse', 'Lion'], correctAnswer: 'Giraffe', explanation: 'Giraffes are the tallest land animals because of their long necks.', category: 'World' },
  { subject: 'gk', grade: 'grade2', type: 'mcq', question: 'How many continents are there in the world?', options: ['5', '6', '7', '8'], correctAnswer: '7', explanation: 'There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.', category: 'World' },

  // Grade 3
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Who is known as the "Father of the Nation" in India?', options: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'Sardar Patel'], correctAnswer: 'Mahatma Gandhi', explanation: "Mahatma Gandhi led India's freedom movement through non-violence and is honoured as the Father of the Nation.", category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'India got independence in 1947.', correctAnswer: 'True', explanation: 'India became independent from British rule on 15 August 1947.', category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Which is the longest river in India?', options: ['Yamuna', 'Godavari', 'Ganga', 'Narmada'], correctAnswer: 'Ganga', explanation: 'The Ganga (Ganges) is the longest river in India.', category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'What is the highest mountain in the world?', options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Nanga Parbat'], correctAnswer: 'Mount Everest', explanation: "Mount Everest, in the Himalayas, is the world's tallest mountain.", category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'Republic Day in India is celebrated on 26th January.', correctAnswer: 'True', explanation: "Republic Day marks the day India's constitution came into effect in 1950.", category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Which is the smallest planet in our solar system?', options: ['Earth', 'Mars', 'Mercury', 'Venus'], correctAnswer: 'Mercury', explanation: 'Mercury is the smallest planet in our solar system.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'The Great Wall of China can easily be seen from space with the naked eye.', correctAnswer: 'False', explanation: 'This is a popular myth — the Great Wall is not visible from space without aid.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Who invented the practical electric light bulb?', options: ['Isaac Newton', 'Thomas Edison', 'Albert Einstein', 'Alexander Graham Bell'], correctAnswer: 'Thomas Edison', explanation: 'Thomas Edison developed the practical electric light bulb.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'How many states does India currently have?', options: ['25', '28', '29', '30'], correctAnswer: '28', explanation: 'India has 28 states and several union territories.', category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'The Olympic Games are held every 4 years.', correctAnswer: 'True', explanation: 'The Summer and Winter Olympic Games are each held once every four years.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Which festival is known as the "Festival of Lights"?', options: ['Holi', 'Diwali', 'Eid', 'Christmas'], correctAnswer: 'Diwali', explanation: 'Diwali celebrates the victory of light over darkness with lamps and fireworks.', category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'Australia is both a country and a continent.', correctAnswer: 'True', explanation: 'Australia is unique in being recognised as both a single country and its own continent.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: "Who wrote India's national anthem?", options: ['Rabindranath Tagore', 'Bankim Chandra Chattopadhyay', 'Sarojini Naidu', 'Subhas Chandra Bose'], correctAnswer: 'Rabindranath Tagore', explanation: 'Rabindranath Tagore wrote "Jana Gana Mana," India\'s national anthem.', category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Which is the largest hot desert in the world?', options: ['Thar Desert', 'Sahara Desert', 'Gobi Desert', 'Kalahari Desert'], correctAnswer: 'Sahara Desert', explanation: 'The Sahara Desert in Africa is the largest hot desert in the world.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'The currency of India is the Rupee.', correctAnswer: 'True', explanation: "The Indian Rupee (₹) is India's official currency.", category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Which planet is known as the "Red Planet"?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correctAnswer: 'Mars', explanation: 'Mars appears red due to iron oxide (rust) on its surface.', category: 'World' },
  { subject: 'gk', grade: 'grade3', type: 'truefalse', question: 'The Taj Mahal is located in Delhi.', correctAnswer: 'False', explanation: 'The Taj Mahal is located in Agra, Uttar Pradesh, not Delhi.', category: 'India' },
  { subject: 'gk', grade: 'grade3', type: 'mcq', question: 'Which is the fastest land animal?', options: ['Lion', 'Cheetah', 'Horse', 'Deer'], correctAnswer: 'Cheetah', explanation: 'The cheetah can run up to 100-120 km/h, making it the fastest land animal.', category: 'World' },
];

const HEALTH_QUESTIONS: Omit<QuizQuestion, 'id'>[] = [
  // Grade 2
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'We should brush our teeth twice a day.', correctAnswer: 'True', explanation: 'Brushing twice a day helps keep teeth clean and prevents cavities.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'Which of these is a healthy food?', options: ['Chips', 'Apple', 'Candy', 'Soda'], correctAnswer: 'Apple', explanation: 'Fruits like apples are healthy and full of vitamins.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'We should wash our hands before eating.', correctAnswer: 'True', explanation: 'Washing hands before eating removes germs and keeps us healthy.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'About how many hours of sleep does a young child need each night?', options: ['2-3 hours', '4-5 hours', '9-11 hours', '15 hours'], correctAnswer: '9-11 hours', explanation: 'Children need about 9 to 11 hours of sleep to stay healthy and grow well.', category: 'Rest' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'Eating too much junk food is good for our body.', correctAnswer: 'False', explanation: 'Junk food has too much sugar, salt, and fat and can harm our health if eaten often.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'What should we cover when we sneeze or cough?', options: ['Eyes', 'Mouth and nose', 'Ears', 'Hands only'], correctAnswer: 'Mouth and nose', explanation: 'Covering our mouth and nose stops germs from spreading to others.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'Drinking water is important for our body.', correctAnswer: 'True', explanation: 'Water helps our body work properly and stay hydrated.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'Which activity keeps our body fit?', options: ['Watching TV all day', 'Exercise', 'Eating candy', 'Sleeping all day'], correctAnswer: 'Exercise', explanation: 'Regular exercise like running and playing keeps our muscles and heart healthy.', category: 'Fitness' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'We should talk to a trusted adult if a stranger makes us feel uncomfortable.', correctAnswer: 'True', explanation: 'Telling a trusted adult keeps us safe when something feels wrong.', category: 'Safety' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'Which of these helps prevent germs from spreading?', options: ['Sharing food', 'Washing hands', 'Not bathing', 'Touching face often'], correctAnswer: 'Washing hands', explanation: 'Washing hands with soap removes germs and prevents illness.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: "It's okay to cross the road without looking both ways.", correctAnswer: 'False', explanation: 'We should always look both ways before crossing the road to stay safe.', category: 'Safety' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'What do our bones need to stay strong?', options: ['Sugar', 'Calcium', 'Salt', 'Oil'], correctAnswer: 'Calcium', explanation: 'Calcium, found in milk and dairy, helps keep our bones strong.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'Wearing a helmet while cycling helps keep us safe.', correctAnswer: 'True', explanation: 'A helmet protects our head if we fall while cycling.', category: 'Safety' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'Which body part helps us see?', options: ['Ears', 'Eyes', 'Nose', 'Tongue'], correctAnswer: 'Eyes', explanation: 'Our eyes let us see the world around us.', category: 'Human Body' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'Eating vegetables is bad for our health.', correctAnswer: 'False', explanation: 'Vegetables give us important vitamins and minerals that keep us healthy.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'What should we do before eating a meal?', options: ['Wash hands', 'Watch TV', 'Run around', 'Skip it'], correctAnswer: 'Wash hands', explanation: 'Washing our hands before meals removes germs and keeps us healthy.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade2', type: 'truefalse', question: 'It is important to rest when we feel sick.', correctAnswer: 'True', explanation: 'Rest helps our body recover and fight off illness.', category: 'Rest' },
  { subject: 'health', grade: 'grade2', type: 'mcq', question: 'Which of these makes up a balanced meal?', options: ['Only candy', 'Only chips', 'Fruits, vegetables, grains and protein', 'Only soda'], correctAnswer: 'Fruits, vegetables, grains and protein', explanation: 'A balanced meal includes a variety of food groups for good health.', category: 'Nutrition' },

  // Grade 3
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'What are the main food groups in a balanced diet?', options: ['Only sweets', 'Fruits, vegetables, grains, proteins and dairy', 'Only meat', 'Only bread'], correctAnswer: 'Fruits, vegetables, grains, proteins and dairy', explanation: 'A balanced diet includes all these food groups for proper growth and health.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Germs can spread through coughing and sneezing.', correctAnswer: 'True', explanation: 'Covering our mouth when coughing or sneezing helps stop germs from spreading.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'What is the best way to clean a small cut?', options: ['Ignore it', 'Wash it with clean water and cover it', 'Rub dirt on it', 'Leave it uncovered outside'], correctAnswer: 'Wash it with clean water and cover it', explanation: 'Cleaning a cut and covering it helps prevent infection.', category: 'First Aid' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Vaccines help protect our body from certain diseases.', correctAnswer: 'True', explanation: 'Vaccines help the body build defences against specific illnesses.', category: 'Wellness' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'About how much physical activity should children get each day?', options: ['None', 'About 15 minutes', 'At least 60 minutes', 'Only on weekends'], correctAnswer: 'At least 60 minutes', explanation: 'Health experts recommend children get at least an hour of physical activity daily.', category: 'Fitness' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'It is okay to talk about our feelings with someone we trust.', correctAnswer: 'True', explanation: 'Sharing our feelings with a trusted adult or friend is a healthy way to manage emotions.', category: 'Wellness' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'Which of these is a sign that we should see a doctor?', options: ['Feeling happy', "A high fever that doesn't go away", 'Being hungry', 'Feeling sleepy at night'], correctAnswer: "A high fever that doesn't go away", explanation: 'A persistent high fever is a sign the body needs medical attention.', category: 'Wellness' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Brushing teeth helps prevent cavities and bad breath.', correctAnswer: 'True', explanation: 'Regular brushing removes food particles and plaque that cause cavities and bad breath.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'What should you do if you feel unwell at school?', options: ['Keep it a secret', 'Tell a teacher or trusted adult', 'Ignore it', 'Go home alone'], correctAnswer: 'Tell a teacher or trusted adult', explanation: "Telling a trusted adult ensures you get help when you're not feeling well.", category: 'Safety' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Drinking sugary drinks every day is good for dental health.', correctAnswer: 'False', explanation: 'Too much sugar can cause tooth decay and cavities.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'Which nutrient mainly helps build strong muscles?', options: ['Sugar', 'Protein', 'Salt', 'Food colouring'], correctAnswer: 'Protein', explanation: 'Protein, found in foods like eggs, beans, and meat, helps build and repair muscles.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Washing fruits and vegetables before eating removes dirt and germs.', correctAnswer: 'True', explanation: 'Rinsing produce under water helps remove dirt, chemicals, and germs.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'What is a good habit for eye health when using screens?', options: ['Sit very close to the screen', 'Take regular breaks and blink often', 'Never blink', 'Use screens in the dark for hours'], correctAnswer: 'Take regular breaks and blink often', explanation: 'Taking breaks from screens helps reduce eye strain.', category: 'Wellness' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Skipping breakfast is a healthy habit.', correctAnswer: 'False', explanation: 'Breakfast gives our body energy to start the day and is an important meal.', category: 'Nutrition' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'Why is handwashing with soap more effective than water alone?', options: ['Soap has a nice smell', 'Soap helps remove germs and dirt more effectively', 'Soap makes hands wet', 'Soap is colourful'], correctAnswer: 'Soap helps remove germs and dirt more effectively', explanation: 'Soap breaks down germs and dirt, making it far more effective at cleaning hands than water alone.', category: 'Hygiene' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'Getting enough sleep helps our brain and body recover.', correctAnswer: 'True', explanation: 'Sleep allows our body and mind to rest, heal, and grow.', category: 'Rest' },
  { subject: 'health', grade: 'grade3', type: 'mcq', question: 'What is a good way to stay safe near roads?', options: ['Run across quickly', 'Use a zebra crossing and look both ways', 'Cross while looking at your phone', 'Cross anywhere without checking'], correctAnswer: 'Use a zebra crossing and look both ways', explanation: 'Using designated crossings and checking both ways keeps us safe from traffic.', category: 'Safety' },
  { subject: 'health', grade: 'grade3', type: 'truefalse', question: 'It is healthy to eat a variety of colourful fruits and vegetables.', correctAnswer: 'True', explanation: 'Different coloured fruits and vegetables provide different vitamins and nutrients.', category: 'Nutrition' },
];

const ALL_QUESTIONS: Omit<QuizQuestion, 'id'>[] = [...SCIENCE_QUESTIONS, ...GK_QUESTIONS, ...HEALTH_QUESTIONS];

export const KNOWLEDGE_QUESTIONS: QuizQuestion[] = ALL_QUESTIONS.map((q, idx) => ({
  ...q,
  id: `${q.subject}_${q.grade}_${idx}`,
}));

export const getQuizQuestions = (subject: KnowledgeSubject, grade: Grade): QuizQuestion[] =>
  KNOWLEDGE_QUESTIONS.filter((q) => q.subject === subject && q.grade === grade);
